Removes call to non-existing generate_unconditional
When running the example, one gets an error:

```
'AudioGen' object has no attribute 'generate_unconditional'
```

AudioGen does not provide a generate_unconditional method. The example looks like a copy-paste mistake from Musicgen readme.