Update spacy dependency so demo project can run
Currently, the musicgen_app.py demo does not run; it fails with the
following error:

> pydantic.errors.PydanticImportError: `pydantic:ConstrainedStr` has been removed in V2.

It is possible to resolve this error by upping the spaCy dependency,
which is what's bringing in the old version of pydantic.

spaCy 3.6.1+ support the new Pydantic version:

https://github.com/explosion/spaCy/releases/tag/v3.6.1